typing:
	python setup_typing.py build_ext --inplace

cfunc:
	python setup_cfunc.py build_ext --inplace

cfunc2:
	python setup_cfunc2.py build_ext --inplace

dp:
	python setup_dp.py build_ext --inplace

dp_eff:
	python setup_dp_eff.py build_ext --inplace

clean:
	rm -rf build
	rm *.c
	rm *.so
